Nodo1 ansible_connection=local ip_estatica=10.4.9.212

[slaves]
Nodo2 ansible_host=Nodo2.local ip_estatica=10.4.8.113
Nodo3 ansible_host=Nodo3.local ip_estatica=10.4.8.34
Nodo4 ansible_host=Nodo4.local ip_estatica=10.4.9.85
Nodo5 ansible_host=Nodo5.local ip_estatica=10.4.9.136
Nodo6 ansible_host=Nodo6.local ip_estatica=10.4.8.213
Nodo7 ansible_host=Nodo7.local ip_estatica=10.4.9.225
Nodo8 ansible_host=Nodo8.local ip_estatica=10.4.8.223
